CREATE TABLE IF NOT EXISTS rate
(
rate_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
currency_name VARCHAR(10) NOT NULL,
exchange_name VARCHAR(10) NOT NULL,
rate DECIMAL(7, 3) NOT NULL
);

INSERT INTO rate (currency_name, exchange_name, rate) VALUES
('DOL', 'RUB', 76.02),
('DOL', 'EURO', 0.94),
('EURO', 'RUB', 80.18),
('EURO', 'DOL', 1.06),
('RUB', 'DOL', 0.013),
('RUB', 'EURO', 0.012);